version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

